//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actiance.App_LocalResources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Actiance.App_LocalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WelcomeMain {
            get {
                return ResourceManager.GetString("WelcomeMain", resourceCulture);
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        internal static string Welcomed {
            get {
                return ResourceManager.GetString("Welcomed", resourceCulture);
            }
        }
        
        internal static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        internal static string OptionError {
            get {
                return ResourceManager.GetString("OptionError", resourceCulture);
            }
        }
        
        internal static string FlagMain {
            get {
                return ResourceManager.GetString("FlagMain", resourceCulture);
            }
        }
        
        internal static string FlagError {
            get {
                return ResourceManager.GetString("FlagError", resourceCulture);
            }
        }
        
        internal static string AskMain {
            get {
                return ResourceManager.GetString("AskMain", resourceCulture);
            }
        }
        
        internal static string AskError {
            get {
                return ResourceManager.GetString("AskError", resourceCulture);
            }
        }
        
        internal static string AskSSN {
            get {
                return ResourceManager.GetString("AskSSN", resourceCulture);
            }
        }
        
        internal static string DLPPhrase {
            get {
                return ResourceManager.GetString("DLPPhrase", resourceCulture);
            }
        }
        
        internal static string ComplianceMessage {
            get {
                return ResourceManager.GetString("ComplianceMessage", resourceCulture);
            }
        }
        
        internal static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        internal static string EmailContent {
            get {
                return ResourceManager.GetString("EmailContent", resourceCulture);
            }
        }
        
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
    }
}
